apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: print-date-
spec:
  taskSpec:
    description: |
      A simple task that prints the date.
    results:
      - name: current-date-unix-timestamp
        description: The current date in unix timestamp format
      - name: very-large-result
        description: A large result
    steps:
      - name: print-date-unix-timestamp
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          date +%s | tee /tekton/results/current-date-unix-timestamp
      - name: very-large-result
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          cat /dev/urandom | head -c 750000 | base64 | tee /tekton/results/very-large-result #about 1 M result
