apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-echo-
spec:
  params:
    - name: HELLO
      value: "Pipeline Hello World!"
  pipelineSpec:
    tasks:
      - name: echo-hello
        taskSpec:
          params:
            - name: HELLO
              default: "Default Hello World!"
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "$(params.HELLO)"
