/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
	scheme "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MyStepsGetter has a method to return a MyStepInterface.
// A group's client should implement this interface.
type MyStepsGetter interface {
	MySteps(namespace string) MyStepInterface
}

// MyStepInterface has methods to work with MyStep resources.
type MyStepInterface interface {
	Create(ctx context.Context, myStep *v1beta1.MyStep, opts v1.CreateOptions) (*v1beta1.MyStep, error)
	Update(ctx context.Context, myStep *v1beta1.MyStep, opts v1.UpdateOptions) (*v1beta1.MyStep, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.MyStep, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.MyStepList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.MyStep, err error)
	MyStepExpansion
}

// mySteps implements MyStepInterface
type mySteps struct {
	client rest.Interface
	ns     string
}

// newMySteps returns a MySteps
func newMySteps(c *TektonV1beta1Client, namespace string) *mySteps {
	return &mySteps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the myStep, and returns the corresponding myStep object, and an error if there is any.
func (c *mySteps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.MyStep, err error) {
	result = &v1beta1.MyStep{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mysteps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MySteps that match those selectors.
func (c *mySteps) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.MyStepList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.MyStepList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mysteps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mySteps.
func (c *mySteps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mysteps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a myStep and creates it.  Returns the server's representation of the myStep, and an error, if there is any.
func (c *mySteps) Create(ctx context.Context, myStep *v1beta1.MyStep, opts v1.CreateOptions) (result *v1beta1.MyStep, err error) {
	result = &v1beta1.MyStep{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mysteps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myStep).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a myStep and updates it. Returns the server's representation of the myStep, and an error, if there is any.
func (c *mySteps) Update(ctx context.Context, myStep *v1beta1.MyStep, opts v1.UpdateOptions) (result *v1beta1.MyStep, err error) {
	result = &v1beta1.MyStep{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mysteps").
		Name(myStep.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myStep).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the myStep and deletes it. Returns an error if one occurs.
func (c *mySteps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mysteps").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mySteps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mysteps").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched myStep.
func (c *mySteps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.MyStep, err error) {
	result = &v1beta1.MyStep{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mysteps").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
