apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: DOCKERFILE
  artifacts:
    inputs:
      - name: source
        description: The precise source code used to build this image.
        value: ""
    outputs:
      - name: coverage
        description: Coverage report that was just built.
        value: "$(tasks.golang-test-task.artifacts.outputs.coverage)"
      - name: image
        description: "Image pushed using kaniko"
        value: "$(tasks.kaniko-task.artifacts.outputs.image)"
  tasks:
    - name: golang-test-task
      artifacts:
        inputs:
          - name: source
            value: ""
        outputs:
          - name: coverage
            value: ""
      taskRef:
        name: golang-test
    - name: kaniko-task
      runafter:
        - golang-test-task
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
      artifacts:
        inputs:
          - name: source
            value: ""
        outputs:
          - name: image
            value: ""
      taskRef:
        name: kaniko
