apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: step-action
spec:
  results:
    - name: res1
  image: alpine
  script: |
    echo "hello" > $(step.results.res1.path)
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: step-action-run
spec:
  TaskSpec:
    results:
      - name: res2
        value: $(steps.action-runner.results.res1)
    steps:
      - name: action-runner
        ref:
          name: step-action
