apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: step-action-run
spec:
  TaskSpec:
    steps:
      - name: action-runner
        ref:
          resolver: git
          params:
            - name: url
              value: https://github.com/chitrangpatel/repo1M.git
            - name: revision
              value: main
            - name: pathInRepo
              value: basic_step.yaml
